#!/bin/bash

set -eo pipefail

SCRIPTPATH="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPTPATH"

if ! command -v uv &> /dev/null; then
    echo "uv utility not found. Please install it: https://docs.astral.sh/uv/getting-started/installation/"
    exit 1
fi

uv run src/museion/cli.py "$@"
